language: php
php:
- 5.3
deploy:
  provider: heroku
  api_key:
    secure: GKQmIAWrUqb7nhdfev2h2WrevQExHv9pG+Wm/ZleMqt8ovsvZR9Aw1Ao8H1dYeT8nekhjHjGckbPdC1NDCtcT0KRRZQRK/4WiWrFzLF4Hgp81yMSQ2uIngS2Wtzb5kRoz5EgYuboxQt3ymyciAEcAVfMKMvpHUSoKUTaarOZYj0=
  app: kmdata-list
  on:
    repo: osu-eng/kmdata-list
